apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i5ay1tvam-nodejs 
  janus-idp.io/tekton: i5ay1tvam-nodejs
  backstage.io/kubernetes-id: i5ay1tvam-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i5ay1tvam-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  